version: '3'

volumes:

  pg_data_kittygram:
  static_kittygram:
  media_kittygram:

services:
  db_kittygram:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data

  backend:
    image: khamaran/kittygram_backend
    env_file: .env
    volumes:
      - static_kittygram:/backend_static
      - media_kittygram:/media
    depends_on:
      - db_kittygram

  frontend:
    image: khamaran/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kittygram:/frontend_static
    depends_on:
      - backend

  gateway:
    image: khamaran/kittygram_gateway
    env_file: .env
    volumes:
      - static_kittygram:/staticfiles
      - media_kittygram:/media
    ports:
      - 9000:80
    depends_on:
      - backend
